name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  native-build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - name: Test
        run: make test
      - name: Build release
        run: make release
