name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  native-tests:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift test
      - name: Build release
        run: swift build -c release
